#!/bin/bash
# Cheers to the primeagen

additional_dirs=("/home/$USER/.local/scripts" "/home/$USER" "/home/$USER/Downloads" "/home/$USER/.config/nvim")
print_list() {
    for dir in "${additional_dirs[@]}"; do
        echo "$dir"
    done
    for dir in $(find /home/${USER}/Personal -maxdepth 1 -mindepth 1 -type d);
	    do echo "$dir";
    done
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$((print_list; find ~/Projects -mindepth 1 -maxdepth 1 -type d) | fzf)
fi

if [[ -z $selected ]];then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

